name: certstream-server
adopt-info: certstream-server
summary: Certstream-server is a server for parsing CTL's. # 79 char long summary
description: |
  Certstream-server is a server written in python3 to aggregate, parse, and stream certificate data from multiple certificate transparency logs. It leverages concurrency to be relatively efficient and handle many clients at the same time.grade: stable # must be 'stable' to release into candidate/stable channels

license: MIT

base: core18
grade: stable
confinement: strict

apps:
  certstream-server:
    command: usr/bin/python3 run_server.py
    plugs:
      - home
      - network
      - network-bind
     
parts: 
  certstream-server:
    source: https://github.com/CaliDog/certstream-server-python
    source-type: git
    plugin: python
    python-version: python3
    requirements: requirements.txt
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - python3
      
    stage-packages:
      - python3
